In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])

In [4]:
a + 1

array([2, 3, 4, 5])

In [5]:
2 ** 3

8

In [6]:
a ** 3 

array([ 1,  8, 27, 64], dtype=int32)

In [7]:
a

array([1, 2, 3, 4])

In [8]:
3 ** a

array([ 3,  9, 27, 81], dtype=int32)

In [9]:
2**a

array([ 2,  4,  8, 16], dtype=int32)

In [10]:
2*a

array([2, 4, 6, 8])

In [11]:
b = np.ones(4)+2

In [12]:
b

array([3., 3., 3., 3.])

In [13]:
a-b

array([-2., -1.,  0.,  1.])

In [14]:
a * b

array([ 3.,  6.,  9., 12.])

In [17]:
t = np.arange(5)

In [18]:
t

array([0, 1, 2, 3, 4])

In [20]:
2**(t + 1) - t

array([ 2,  3,  6, 13, 28])

In [21]:
2**(t + 1)

array([ 2,  4,  8, 16, 32], dtype=int32)

In [22]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])

In [23]:
a==b

array([False,  True, False,  True])

In [24]:
a > b

array([False, False,  True, False])

In [27]:
c = np.array([1,2,3,4])

In [28]:
np.array_equal(a,b)

False

In [29]:
np.array_equal(a,c)

True

In [30]:
e = np.array([1,1,0,0], dtype=bool)
f = np.array([1,0,1,0], dtype=bool)

In [32]:
np.logical_or(e,f)

array([ True,  True,  True, False])

In [33]:
np.logical_xor(e,f)

array([False,  True,  True, False])

In [34]:
np.logical_and(e,f)

array([ True, False, False, False])

In [35]:
np.logical_not(e,f)

array([False, False,  True,  True])

In [37]:
np.logical_not(e)

array([False, False,  True,  True])

In [42]:
g = np.arange(5)
np.sin(g)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [45]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [49]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [47]:
g

array([0, 1, 2, 3, 4])

In [48]:
np.exp(0)

1.0

In [50]:
y = np.array([1,2])

In [52]:
g+y

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

In [53]:
help(np.triu)

Help on function triu in module numpy:

triu(m, k=0)
    Upper triangle of an array.
    
    Return a copy of a matrix with the elements below the `k`-th diagonal
    zeroed.
    
    Please refer to the documentation for `tril` for further details.
    
    See Also
    --------
    tril : lower triangle of an array
    
    Examples
    --------
    >>> np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
    array([[ 1,  2,  3],
           [ 4,  5,  6],
           [ 0,  8,  9],
           [ 0,  0, 12]])



In [66]:
a = np.tril(np.ones((4,4)),0)

In [67]:
a

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [68]:
a.T

array([[1., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [69]:
help(np.allclose)

Help on function allclose in module numpy:

allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
    Returns True if two arrays are element-wise equal within a tolerance.
    
    The tolerance values are positive, typically very small numbers.  The
    relative difference (`rtol` * abs(`b`)) and the absolute difference
    `atol` are added together to compare against the absolute difference
    between `a` and `b`.
    
    If either array contains one or more NaNs, False is returned.
    Infs are treated as equal if they are in the same place and of the same
    sign in both arrays.
    
    Parameters
    ----------
    a, b : array_like
        Input arrays to compare.
    rtol : float
        The relative tolerance parameter (see Notes).
    atol : float
        The absolute tolerance parameter (see Notes).
    equal_nan : bool
        Whether to compare NaN's as equal.  If True, NaN's in `a` will be
        considered equal to NaN's in `b` in the output array.
    
        .. 

In [70]:
x= np.array([1,2,3,4])

In [71]:
np.sum(x)

10

In [72]:
x.sum()

10

In [73]:
h=np.array([[1,1],[2,2]])

In [74]:
h

array([[1, 1],
       [2, 2]])

In [75]:
x.sum(axis=0)

10

In [76]:
h.sum(axis=0)

array([3, 3])

In [77]:
h[:,0].sum(),h[:,1].sum()

(3, 3)

In [78]:
h.sum(axis=1)

array([2, 4])

In [79]:
h[0,:].sum(),h[1,:].sum()

(2, 4)

In [80]:
h.min()

1

In [81]:
h.max()

2

In [82]:
i =np.array([1,2,3,4,5])

In [83]:
i.min()

1

In [84]:
i.max()

5

In [86]:
i.argmax()

4

In [87]:
i.argmin()

0

In [88]:
np.all([True, True, False])

False

In [90]:
np.any([True, True, False])

True

In [91]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])

x.median()

In [94]:
x.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [97]:
np.median(x)

1.5

In [98]:
np.median(y,axis=-1)

array([2., 5.])